server:
  port: 8204
  servlet:
    context-path: /

# 服务节点,要求分布式下每个节点不同
node: 01

dubbo:
  registry:
    address: @zookeeper.url@
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

spring:
  application:
    name: xxpay-merchant
  cache:
    type: redis
  redis:
    host: @redis.ip@
    port: @redis.port@
    timeout: 1000
    database: 1
    password: @redis.pass@
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 100
        min-idle: 1
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    serialization:
      INDENT_OUTPUT: true
  servlet:
    multipart:
      max-file-size: 2MB
  profiles:
     active: prod

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:F:/backup/division.sqlite
    username:
    password:

# JWT
jwt:
  cookie: XxPay_Mch_Token
  secret: XxpPayGood
  expiration: 604800 # 7天 token串内记录的过期时间，目前修改为redis认证方式，此值无需验证.

config:
  appId: wx077cb62e341f8a5c
  appSecret: e663ea068f3e4f952f143de1432a35c2
  token:
  aesKey:
  mchApiUrl: @mch.site.url@/api
  payUrl: @pay.site.url@/api
  notifyUrl: @mch.site.url@/api/payment/notify
  downloadDemoPath: @download.demo.path@
  uploadMchStaticDir: @upload.mch.static.dir@
  uploadMchStaticViewUrl: @upload.mch.static.view.url@
  uploadAppUpdateDir: @upload.app.update.dir@
  mbrAddUrl: @mbr.site.url@/api/auth # 会员系统领卡

sqlit:
  file:
    path: jdbc:sqlite:@sqlit.file.path@

logging:
  level:
    org.xxpay.service.dao.mapper: debug


